name: my_api_app
description: Uma aplicação Dart/Flutter que consome uma API HTTP.
version: 1.0.0
publish_to: 'none' # Define que o projeto não será publicado no pub.dev.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Pacote para realizar requisições HTTP
  http: ^1.2.1

  # Pacote opcional para manipular JSON de forma mais robusta
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Ferramenta para gerar código para JSON (caso você use build_runner e json_serializable)
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # Adicione assets (imagens, ícones) se necessário
  assets:
    - assets/images/

  # Adicione fontes personalizadas se necessário
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
